apiVersion: v1
kind: Service
metadata:
  name: broker-app
spec:
  selector:
    app: broker-app
  ports:
  - name: mqtt
    protocol: TCP
    port: 1883
    targetPort: 1883
  - name: websockets
    protocol: TCP
    port: 9001
    targetPort: 9001
