apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-app
  template:
    metadata:
      labels:
        app: broker-app
    spec:
      containers:
      - name: broker-app
        image: broker-app:latest
        ports:
        - containerPort: 1883
